# Generated by Django 5.0.6 on 2024-05-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passwordreset',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='passwordreset',
            index_together=set(),
        ),
    ]
