# Generated by Django 5.0.6 on 2024-05-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_passwordreset_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passwordreset',
            unique_together={('user', 'created_at')},
        ),
        migrations.AlterIndexTogether(
            name='passwordreset',
            index_together={('user', 'created_at')},
        ),
    ]
