# Generated by Django 5.0.6 on 2024-05-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_passwordreset_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
